LeHungCuong_2122110266/Areas/Admin/Controllers/CategoryController.cs
using LeHungCuong_2122110266.Context;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LeHungCuong_2122110266.Areas.Admin.Controllers
{
    public class CategoryController : Controller
    {
        WebAspDbEntities db = new WebAspDbEntities();

        // GET: Admin/Category
        public ActionResult Index(string Search, string currentFilter, int? page)
        {
            var listCategory = new List<Category>();
            if (Search != null)
            {
                page = 1;
            }
            else
            {
                Search = currentFilter;
            }
            if (!String.IsNullOrEmpty(Search))
            {
                listCategory = db.Category.Where(n => n.Name.Contains(Search)).ToList();
            }
            else
            {
                listCategory = db.Category.ToList();
            }
            ViewBag.CurrentFilter = Search;
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            listCategory = listCategory.OrderByDescending(n => n.Id).ToList();

            if (Request.IsAjaxRequest())
            {
                return PartialView("_CategoryList", listCategory.ToPagedList(pageNumber, pageSize));
            }

            return View(listCategory.ToPagedList(pageNumber, pageSize));
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Category category)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    // Kiểm tra file được upload
                    if (category.ImageUpLoad != null && category.ImageUpLoad.ContentLength > 0)
                    {
                        string fileName = Path.GetFileNameWithoutExtension(category.ImageUpLoad.FileName);
                        string extension = Path.GetExtension(category.ImageUpLoad.FileName);

                        // Tạo tên file mới để tránh trùng lặp
                        fileName = fileName + "_" + DateTime.Now.ToString("yyyyMMddHHmmss") + extension;

                        // Đường dẫn lưu file
                        string path = Path.Combine(Server.MapPath("~/Content/images/items/"), fileName);

                        // Lưu file
                        category.ImageUpLoad.SaveAs(path);

                        // Gán tên file vào thuộc tính Image
                        category.Image = fileName;
                    }

                    // Lưu thông tin vào cơ sở dữ liệu
                    category.CreatedAt = DateTime.Now;
                    db.Category.Add(category);
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Không thể tạo danh mục. Lỗi: " + ex.Message);
                }
            }
            return View(category);
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            var category = db.Category.Where(n => n.Id == id).FirstOrDefault();
            return View(category);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var category = db.Category.Where(n => n.Id == id).FirstOrDefault();
            return View(category);
        }

        [HttpPost]
        public ActionResult Edit(Category category, int id)
        {
            var existingCategory = db.Category.Where(n => n.Id == id).FirstOrDefault();
            if (existingCategory == null)
            {
                return HttpNotFound();
            }

            if (category.ImageUpLoad != null && category.ImageUpLoad.ContentLength > 0)
            {
                // Nếu có hình mới, thực hiện lưu hình mới
                string fileName = Path.GetFileNameWithoutExtension(category.ImageUpLoad.FileName);
                string extension = Path.GetExtension(category.ImageUpLoad.FileName);
                fileName = fileName + "_" + long.Parse(DateTime.Now.ToString("yyyyMMddhhmmss")) + extension;
                category.Image = fileName;

                // Lưu hình vào thư mục
                category.ImageUpLoad.SaveAs(Path.Combine(Server.MapPath("~/Content/images/items/"), fileName));
            }
            else
            {
                // Nếu không có hình mới, giữ lại hình cũ
                category.Image = existingCategory.Image;
            }

            // Cập nhật các thông tin khác
            existingCategory.Name = category.Name;
            existingCategory.Deleted = category.Deleted;
            existingCategory.ShowOnHomePage = category.ShowOnHomePage;
            existingCategory.DisplayOrder = category.DisplayOrder;
            existingCategory.Image = category.Image; // Giữ hình cũ hoặc cập nhật hình mới
            existingCategory.UpdatedAt = DateTime.Now;

            db.Entry(existingCategory).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var category = db.Category.Where(n => n.Id == id).FirstOrDefault();
            return View(category);
        }

        [HttpPost]
        public ActionResult Delete(Category category)
        {
            try
            {
                var categoryToDelete = db.Category.Where(n => n.Id == category.Id).FirstOrDefault();
                db.Category.Remove(categoryToDelete);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Error occurred while deleting the category.");
                return View(category);
            }
        }
    }
}

LeHungCuong_2122110266/Controllers/CategoryController.cs
using LeHungCuong_2122110266.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LeHungCuong_2122110266.Controllers
{
    public class CategoryController : Controller
    {
        WebAspDbEntities db = new WebAspDbEntities();
        // GET: Category
        public ActionResult Category()
        {
            var listCategory = db.Category.ToList();
            return View(listCategory);
        }
        //public ActionResult ProductCategory(int Id)
        //{
        //    var products = db.Product.Where(n => n.CategoryId == Id).ToList();
        //    return View(products);  // Truyền danh sách sản ph
        //}
        public ActionResult ProductCategory(int Id, int page = 1, int pageSize = 1)
        {
            List<Product> listProduct;

            if (Id == 0) // Nếu ID là 0, lấy tất cả sản phẩm
            {
                listProduct = db.Product.ToList();
            }
            else
            {
                listProduct = db.Product.Where(n => n.CategoryId == Id).ToList();
            }

            // Tính tổng số sản phẩm
            int totalProducts = listProduct.Count;

            // Phân trang
            var paginatedProducts = listProduct.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            // Truyền dữ liệu cần thiết sang ViewBag
            ViewBag.CurrentCategoryId = Id;
            ViewBag.CurrentPage = page;
            ViewBag.TotalPages = (int)Math.Ceiling((double)totalProducts / pageSize);
            ViewBag.PageSize = pageSize;

            return View(paginatedProducts);
        }
    }
}

LeHungCuong_2122110266/Areas/Admin/Views/Category/Create.cshtml
@model LeHungCuong_2122110266.Context.Category

@{
    ViewBag.Title = "Create";
}

<h2>Thêm Danh mục</h2>

@using (Html.BeginForm("Create", "Category", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Category</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="ImageUpLoad" />
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Slug, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Slug, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Slug, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ShowOnHomePage, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.ShowOnHomePage)
                @Html.ValidationMessageFor(model => model.ShowOnHomePage, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DisplayOrder, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DisplayOrder, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DisplayOrder, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CreatedAt, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CreatedAt, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CreatedAt, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Quay về", "Index")
</div>

LeHungCuong_2122110266/Areas/Admin/Views/Category/Delete.cshtml
@model LeHungCuong_2122110266.Context.Category

@{
    ViewBag.Title = "Delete";
}

<h2 class="text-danger">Xóa danh mục</h2>

<div class="alert alert-warning">
    <h4><i class="fas fa-exclamation-triangle"></i> Bạn có muốn xóa danh mục này?</h4>
</div>

<div class="card">
    <div class="card-header bg-danger text-white">
        <h5>Chi tiết</h5>
    </div>
    <div class="card-body">
        <dl class="row">
            <dt class="col-sm-3 font-weight-bold">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt class="col-sm-3 font-weight-bold">
                @Html.DisplayNameFor(model => model.Image)
            </dt>
            <dd class="col-sm-9">
                <img src="@Url.Content("~/Content/images/items/" + Model.Image)" alt="Category Image" class="img-thumbnail" style="max-width: 150px;" />
            </dd>

            <dt class="col-sm-3 font-weight-bold">
                @Html.DisplayNameFor(model => model.Slug)
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Slug)
            </dd>

            <dt class="col-sm-3 font-weight-bold">
                @Html.DisplayNameFor(model => model.ShowOnHomePage)
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.ShowOnHomePage)
            </dd>

            <dt class="col-sm-3 font-weight-bold">
                @Html.DisplayNameFor(model => model.DisplayOrder)
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.DisplayOrder)
            </dd>

            <dt class="col-sm-3 font-weight-bold">
                @Html.DisplayNameFor(model => model.CreatedAt)
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.CreatedAt)
            </dd>

            <dt class="col-sm-3 font-weight-bold">
                @Html.DisplayNameFor(model => model.UpdatedAt)
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.UpdatedAt)
            </dd>
        </dl>
    </div>
</div>

<div class="mt-4">
    @using (Html.BeginForm("Delete", "Category", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <input type="hidden" name="id" value="@Model.Id" />

        <div class="text-center">
            <button type="submit" class="btn btn-danger">
                <i class="fas fa-trash-alt"></i> xác nhận xóa
            </button>
            <a href="@Url.Action("Index", "Category")" class="btn btn-secondary">
                <i class="fas fa-arrow-left"></i> quay về
            </a>
        </div>
    }
</div>

LeHungCuong_2122110266/Areas/Admin/Views/Category/Details.cshtml
@model LeHungCuong_2122110266.Context.Category

@{
    ViewBag.Title = "Details";
}

<div class="container mt-4">
    <div class="card shadow-sm">
        <div class="card-header bg-primary text-white">
            <h3 class="mb-0">Danh mục</h3>
        </div>
        <div class="card-body">
            <h4 class="text-muted">Chi tiết</h4>
            <hr />
            <div class="row">
                <div class="col-md-6">
                    <dl class="row">
                        <dt class="col-sm-4">Name</dt>
                        <dd class="col-sm-8">@Html.DisplayFor(model => model.Name)</dd>

                        <dt class="col-sm-4">Avatar</dt>
                        <dd class="col-sm-8">
                            <img src="@Url.Content("~/Content/images/items/" + Model.Image)" alt="Category Avatar" class="img-fluid rounded" />
                        </dd>

                        <dt class="col-sm-4">Slug</dt>
                        <dd class="col-sm-8">@Html.DisplayFor(model => model.Slug)</dd>
                    </dl>
                </div>

                <div class="col-md-6">
                    <dl class="row">
                        <dt class="col-sm-4">Show on Homepage</dt>
                        <dd class="col-sm-8">@Html.DisplayFor(model => model.ShowOnHomePage)</dd>

                        <dt class="col-sm-4">Display Order</dt>
                        <dd class="col-sm-8">@Html.DisplayFor(model => model.DisplayOrder)</dd>
                    </dl>
                </div>
            </div>

            <h4 class="text-muted mt-4">Additional Information</h4>
            <hr />
            <dl class="row">
                <dt class="col-sm-3">Deleted</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.Deleted)</dd>

                <dt class="col-sm-3">Created On</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.CreatedAt)</dd>

                <dt class="col-sm-3">Updated On</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.UpdatedAt)</dd>
            </dl>
        </div>
        <div class="card-footer text-end">
            @Html.ActionLink("CHỉnh sữa", "Edit", new { id = Model.Id }, new { @class = "btn btn-primary me-2" })
            @Html.ActionLink("quay về", "Index", null, new { @class = "btn btn-secondary" })
        </div>
    </div>
</div>

LeHungCuong_2122110266/Areas/Admin/Views/Category/Edit.cshtml
@model LeHungCuong_2122110266.Context.Category

@{
    ViewBag.Title = "Edit";
}

<h2 class="text-center mb-4">Chỉnh sữa danh mục</h2>

@using (Html.BeginForm("Edit", "Category", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="container">
        <div class="card shadow-sm">
            <div class="card-body">
                <h4 class="card-title">Chi tiết</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "alert alert-danger" })
                @Html.HiddenFor(model => model.Id)
                @Html.HiddenFor(model => model.CreatedAt)
                <div class="row mb-3">
                    <label class="col-md-3 col-form-label">@Html.LabelFor(model => model.Name)</label>
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row mb-3">
                    <label class="col-md-3 col-form-label">@Html.LabelFor(model => model.Image)</label>
                    <div class="col-md-9">
                        <!-- Hiển thị hình ảnh hiện tại -->
                        @if (!string.IsNullOrEmpty(Model.Image))
                        {
                            <img src="~/Content/images/items/" alt="Current Image" class="img-thumbnail" style="max-width: 200px;" />
                        }
                        <input type="file" name="ImageUpload" class="form-control mt-2" />
                        @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
                    </div>
                </div>

                @*<div class="row mb-3">
            <label class="col-md-3 col-form-label">@Html.LabelFor(model => model.Slug)</label>
            <div class="col-md-9">
                @Html.EditorFor(model => model.Slug, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Slug, "", new { @class = "text-danger" })
            </div>
        </div>*@

                <!-- Checkbox Inputs -->
                <div class="row mb-3">
                    <label class="col-md-3 col-form-label">@Html.LabelFor(model => model.ShowOnHomePage)</label>
                    <div class="col-md-9">
                        <div class="form-check">
                            @Html.EditorFor(model => model.ShowOnHomePage)
                            @Html.ValidationMessageFor(model => model.ShowOnHomePage, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="row mb-3">
                    <label class="col-md-3 col-form-label">@Html.LabelFor(model => model.DisplayOrder)</label>
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.DisplayOrder, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DisplayOrder, "", new { @class = "text-danger" })
                    </div>
                </div>

                <!-- Submit Button -->
                <div class="row">
                    <div class="col-md-9 offset-md-3">
                        <button type="submit" class="btn btn-primary">Lưu</button>
                        @Html.ActionLink("Quay về", "Index", null, new { @class = "btn btn-secondary ms-2" })
                    </div>
                </div>
            </div>
        </div>
    </div>
}

LeHungCuong_2122110266/Areas/Admin/Views/Category/Index.cshtml
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<LeHungCuong_2122110266.Context.Category>

<h2>Quản lý danh mục</h2>
<p>
    @Html.ActionLink("Thêm danh mục", "Create", null, new { @class = "btn btn-primary" })
</p>

@using (Html.BeginForm("Index", "Category", FormMethod.Get, new { id = "searchForm" }))
{
    <p>
        Tìm tên danh mục: @Html.TextBox("Search", ViewBag.CurrentFilter as string)
        <input type="submit" value="Tìm kiếm" />
    </p>
}

<div id="categoryList">
    @Html.Partial("_CategoryList", Model)
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    // Xử lý tìm kiếm bằng AJAX
    $("#searchForm").on("submit", function (e) {
        e.preventDefault();
        var url = $(this).attr("action");
        var query = $("#Search").val();

        $.get(url, { Search: query }, function (data) {
            $("#categoryList").html(data);
        });
    });

    // Xử lý phân trang bằng AJAX
    $(document).on("click", ".pagination a", function (e) {
        e.preventDefault();
        var url = $(this).attr("href");

        $.get(url, function (data) {
            $("#categoryList").html(data);
        });
    });
</script>

LeHungCuong_2122110266/Areas/Admin/Views/Category/_CategoryList.cshtml
@model PagedList.IPagedList<LeHungCuong_2122110266.Context.Category>
@using PagedList
@using PagedList.Mvc

<table class="table">
    <tr>
        <th>@Html.DisplayNameFor(model => model.FirstOrDefault().Name)</th>
        <th style="width:200px">@Html.DisplayNameFor(model => model.FirstOrDefault().Image)</th>
        <th>@Html.DisplayNameFor(model => model.FirstOrDefault().Slug)</th>
        <th>@Html.DisplayNameFor(model => model.FirstOrDefault().ShowOnHomePage)</th>
        <th>@Html.DisplayNameFor(model => model.FirstOrDefault().DisplayOrder)</th>
        <th>@Html.DisplayNameFor(model => model.FirstOrDefault().CreatedAt)</th>
        <th>@Html.DisplayNameFor(model => model.FirstOrDefault().UpdatedAt)</th>

        <th>@Html.DisplayNameFor(model => model.FirstOrDefault().Deleted)</th>
        <th>Actions</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.Name)</td>
            <td>
                <img src="@Url.Content("~/content/images/items/" + item.Image)" alt="Category Image" class="img-thumbnail" style="width: 200px;">
            </td>
            <td>@Html.DisplayFor(modelItem => item.Slug)</td>
            <td>@Html.DisplayFor(modelItem => item.ShowOnHomePage)</td>
            <td>@Html.DisplayFor(modelItem => item.DisplayOrder)</td>
            <td>@Html.DisplayFor(modelItem => item.CreatedAt)</td>
            <td>@Html.DisplayFor(modelItem => item.UpdatedAt)</td>
            <td>@Html.DisplayFor(modelItem => item.Deleted)</td>
            <td>
                @Html.ActionLink("Sửa", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Chi Tiết", "Details", new { id = item.Id }) |
                @Html.ActionLink("Xóa", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
</table>

<nav aria-label="Pagination" class="mt-4">
    <ul class="pagination justify-content-center">
        @if (Model.HasPreviousPage)
        {
            <li class="page-item">
                <a class="page-link" href="?page=@(Model.PageNumber - 1)" aria-label="Previous">
                    &laquo; Trước
                </a>
            </li>
        }
        else
        {
            <li class="page-item disabled">
                <span class="page-link" aria-hidden="true">&laquo; Trước</span>
            </li>
        }

        @for (int i = 1; i <= Model.PageCount; i++)
        {
            if (i == Model.PageNumber)
            {
                <li class="page-item active">
                    <span class="page-link">@i</span>
                </li>
            }
            else
            {
                <li class="page-item">
                    <a class="page-link" href="?page=@i">@i</a>
                </li>
            }
        }

        @if (Model.HasNextPage)
        {
            <li class="page-item">
                <a class="page-link" href="?page=@(Model.PageNumber + 1)" aria-label="Next">
                    Tiếp &raquo;
                </a>
            </li>
        }
        else
        {
            <li class="page-item disabled">
                <span class="page-link" aria-hidden="true">Tiếp &raquo;</span>
            </li>
        }
    </ul>
</nav>