LeHungCuong_2122110266/Areas/Admin/Controllers/ProductController.cs
using LeHungCuong_2122110266.Context;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList.Mvc;
namespace LeHungCuong_2122110266.Areas.Admin.Controllers
{
    public class ProductController : Controller
    {

        WebAspDbEntities db = new WebAspDbEntities();

        // GET: Admin/Product
        public ActionResult Index(string Search, string currentFilter, int? page)
        {
            var listProduct = new List<Product>();
            if (Search != null)
            {
                page = 1;
            }
            else
            {
                Search = currentFilter;
            }
            if (!string.IsNullOrEmpty(Search))
            {
                listProduct = db.Product.Where(n => n.Name.Contains(Search)).ToList();
            }
            else
            {
                listProduct = db.Product.ToList();
            }
            ViewBag.CurrentFilter = Search;
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            listProduct = listProduct.OrderByDescending(n => n.Id).ToList();

            if (Request.IsAjaxRequest())
            {
                return PartialView("_ProductList", listProduct.ToPagedList(pageNumber, pageSize));
            }

            return View(listProduct.ToPagedList(pageNumber, pageSize));
        }
        [HttpGet]
        public ActionResult Create()
        {

            this.LoadData();

            return View();
        }
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult Create(Product product)
        {
            this.LoadData();
            if (ModelState.IsValid)
            {
                try
                {
                    if (product.ImageUpLoad != null && product.ImageUpLoad.ContentLength > 0)
                    {
                        string fileName = Path.GetFileNameWithoutExtension(product.ImageUpLoad.FileName);
                        string extension = Path.GetExtension(product.ImageUpLoad.FileName);
                        fileName = fileName + "_" + long.Parse(DateTime.Now.ToString("yyyyMMddhhmmss")) + extension;
                        product.Image = fileName;
                        product.ImageUpLoad.SaveAs(Path.Combine(Server.MapPath("~/Content/images/items/"), fileName));
                    }
                    product.CreatedAt = DateTime.Now;
                    db.Product.Add(product);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    return RedirectToAction("Index");
                }
            }
            return View(product);
        }


        [HttpGet]
        public ActionResult Details(int id)
        {
            var Product = db.Product.Where(n => n.Id == id).FirstOrDefault();
            return View(Product);
        }


        [HttpGet]
        public ActionResult Delete(int id)
        {
            var Product = db.Product.Where(n => n.Id == id).FirstOrDefault();
            return View(Product);
        }
        [HttpPost]
        public ActionResult Delete(Product product)
        {
            var Product = db.Product.Where(n => n.Id == product.Id).FirstOrDefault();
            db.Product.Remove(Product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var Product = db.Product.Where(n => n.Id == id).FirstOrDefault();
            return View(Product);
        }
        [HttpPost]
        public ActionResult Edit(Product product, int id)
        {
            var existingProduct = db.Product.Where(n => n.Id == id).FirstOrDefault();
            if (existingProduct == null)
            {
                return HttpNotFound();
            }


            if (product.ImageUpLoad != null && product.ImageUpLoad.ContentLength > 0)
            {
                // Nếu có hình mới, thực hiện lưu hình mới
                string fileName = Path.GetFileNameWithoutExtension(product.ImageUpLoad.FileName);
                string extension = Path.GetExtension(product.ImageUpLoad.FileName);
                fileName = fileName + "_" + long.Parse(DateTime.Now.ToString("yyyyMMddhhmmss")) + extension;
                product.Image = fileName;

                // Lưu hình vào thư mục
                product.ImageUpLoad.SaveAs(Path.Combine(Server.MapPath("~/Content/images/items/"), fileName));
            }
            else
            {
                // Nếu không có hình mới, giữ lại hình cũ
                product.Image = existingProduct.Image;
            }

            // Cập nhật các thông tin khác
            existingProduct.Name = product.Name;
            existingProduct.CategoryId = product.CategoryId;
            existingProduct.BrandId = product.BrandId;
            existingProduct.ShortDes = product.ShortDes;
            existingProduct.FullDescription = product.FullDescription;
            existingProduct.Price = product.Price;
            existingProduct.PriceDiscount = product.PriceDiscount;
            existingProduct.Deleted = product.Deleted;
            existingProduct.ShowOnHomePage = product.ShowOnHomePage;
            existingProduct.Image = product.Image; // Giữ hình cũ hoặc cập nhật hình mới
            existingProduct.UpdatedAt = DateTime.Now;



            db.Entry(existingProduct).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Index");
        }
        void LoadData()
        {
            Common objCommon = new Common();
            ListtoDataTableConverter converter = new ListtoDataTableConverter();

            var listCategory = db.Category.ToList();
            DataTable dtCategory = converter.ToDataTable(listCategory);
            ViewBag.ListCategory = objCommon.ToSelectList(dtCategory, "Id", "Name");

            var listBrands = db.Brand.ToList();
            DataTable dtBrands = converter.ToDataTable(listBrands);
            ViewBag.ListBrands = objCommon.ToSelectList(dtBrands, "Id", "Name");

            List<ProductType> listProductType = new List<ProductType>();
            ProductType productType = new ProductType();
            productType.Id = 1;
            productType.Name = "Giảm giá sốc";
            listProductType.Add(productType);

            productType = new ProductType();
            productType.Id = 2;
            productType.Name = "Đề xuất";
            listProductType.Add(productType);

            DataTable dtProductType = converter.ToDataTable(listProductType);
            ViewBag.ProductType = objCommon.ToSelectList(dtProductType, "Id", "Name");
        }
    }
}

LeHungCuong_2122110266/Controllers/CartController.cs
using LeHungCuong_2122110266.Context;
using LeHungCuong_2122110266.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
namespace LeHungCuong_2122110266.Controllers
{
    public class CartController : Controller
    {
        private WebAspDbEntities db = new WebAspDbEntities();

        // Display Shopping Cart
        // Display Shopping Cart
        public ActionResult ShoppingCart()
        {
            List<CartModel> cart = Session["cart"] as List<CartModel>;

            if (cart == null || !cart.Any())
            {
                Session["count"] = 0; // Nếu giỏ hàng trống, cập nhật count về 0
            }

            return View(cart);
        }


        // Add Product to Cart
        public ActionResult AddToCart(int id, int quantity)
        {
            try
            {
                List<CartModel> cart = Session["cart"] as List<CartModel> ?? new List<CartModel>();
                int index = cart.FindIndex(item => item.Product.Id == id);

                if (index != -1)
                {
                    // If the product exists in the cart, update the quantity
                    cart[index].Quantity += quantity;
                }
                else
                {
                    // Add new product to the cart
                    var product = db.Product.Find(id);
                    if (product == null) return Json(new { success = false, message = "Sản phẩm không tồn tại" });

                    cart.Add(new CartModel { Product = product, Quantity = quantity });
                }

                // Update session
                Session["cart"] = cart;
                Session["count"] = cart.Count;

                return Json(new { success = true, message = "Thêm vào giỏ hàng thành công", cartCount = cart.Count });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message });
            }
        }

        // Remove Product from Cart

        public ActionResult Remove(int id)
        {
            try
            {
                List<CartModel> cart = Session["cart"] as List<CartModel>;

                if (cart != null && cart.Any())
                {
                    cart.RemoveAll(item => item.Product.Id == id);
                    Session["cart"] = cart;
                    Session["count"] = cart.Count;

                    decimal totalPrice = CalculateTotalPrice(cart, out decimal discount);
                    decimal totalWithDiscount = totalPrice - discount;

                    // Nếu giỏ hàng trống, cập nhật count về 0
                    if (cart.Count == 0)
                    {
                        Session["count"] = 0;
                    }

                    return Json(new
                    {
                        success = true,
                        message = "Xóa sản phẩm thành công",
                        cartCount = cart.Count,
                        totalPrice,
                        discount,
                        totalWithDiscount,
                        cartEmpty = cart.Count == 0
                    }, JsonRequestBehavior.AllowGet);
                }

                return Json(new { success = false, message = "Giỏ hàng rỗng" });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message });
            }
        }


        // Update Product Quantity in Cart

        public ActionResult UpdateQuantity(int id, int quantity)
        {
            try
            {
                List<CartModel> cart = Session["cart"] as List<CartModel>;
                int index = cart?.FindIndex(item => item.Product.Id == id) ?? -1;

                if (index != -1)
                {
                    cart[index].Quantity = quantity;
                    Session["cart"] = cart;

                    decimal totalPrice = CalculateTotalPrice(cart, out decimal discount);
                    decimal totalWithDiscount = totalPrice - discount;

                    return Json(new
                    {
                        success = true,
                        message = "Cập nhật số lượng thành công",
                        totalPrice,
                        discount,
                        totalWithDiscount
                    }, JsonRequestBehavior.AllowGet);
                }

                return Json(new { success = false, message = "Sản phẩm không tồn tại trong giỏ hàng" });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message });
            }
        }


        // Utility: Calculate Total Price and Discount
        private decimal CalculateTotalPrice(List<CartModel> cart, out decimal discount)
        {
           decimal totalPrice = 0;
    discount = 0;

    foreach (var item in cart)
    {
        // Không cần kiểm tra null vì Price và PriceDiscount là kiểu double
        decimal price = (decimal)item.Product.Price;
        decimal priceDiscount = (decimal)item.Product.PriceDiscount;

        if (item.Product.TypeId == 1) // If discounted
        {
            price -= priceDiscount;
        }

        totalPrice += price * item.Quantity;
        discount += priceDiscount * item.Quantity;
    }

    return totalPrice;
        }

        // View Cart Summary
        public ActionResult CartSummary()
        {
            var cart = Session["cart"] as List<CartModel>;
            if (cart == null || !cart.Any())
            {
                return View(); // Giỏ hàng trống
            }

            decimal totalPrice = CalculateTotalPrice(cart, out decimal discount);
            decimal totalWithDiscount = totalPrice - discount;

            // Sau khi tính toán giá trị, xóa giỏ hàng khỏi session
            Session["cart"] = null;

            // Đưa các giá trị cần thiết vào ViewBag để hiển thị
            ViewBag.TotalPrice = totalPrice;
            ViewBag.Discount = discount;
            ViewBag.TotalWithDiscount = totalWithDiscount;

            return View(cart);
        }


    }
}

LeHungCuong_2122110266/Controllers/ProductController.cs
using LeHungCuong_2122110266.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LeHungCuong_2122110266.Controllers
{
    public class ProductController : Controller
    {
        WebAspDbEntities db = new WebAspDbEntities();
        // GET: Product
        public ActionResult Detail(int Id)
        {
            var objProduct = db.Product.Where(n => n.Id == Id).FirstOrDefault();
            return View(objProduct);
        }
        public ActionResult ListingGrid()
        {
            return View();
        }
        public ActionResult ListingList(int Id, int page = 1, int pageSize = 1)
        {
            List<Product> listProduct;

            if (Id == 0) // Nếu ID là 0, lấy tất cả sản phẩm
            {
                listProduct = db.Product.ToList();
            }
            else
            {
                listProduct = db.Product.Where(n => n.CategoryId == Id).ToList();
            }

            // Tính tổng số sản phẩm
            int totalProducts = listProduct.Count;

            // Phân trang
            var paginatedProducts = listProduct.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            // Truyền dữ liệu cần thiết sang ViewBag
            ViewBag.CurrentCategoryId = Id;
            ViewBag.CurrentPage = page;
            ViewBag.TotalPages = (int)Math.Ceiling((double)totalProducts / pageSize);
            ViewBag.PageSize = pageSize;

            return View(paginatedProducts);
        }
    }
}

LeHungCuong_2122110266/Views/Product/Detail.cshtml
@model LeHungCuong_2122110266.Context.Product
@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script type="text/javascript">
    $(function () {
        $("#addtocart").click(function () {
            var model = {};
            // lấy id sản phẩm
            model.Id = @Model.Id;
            // lấy số lượng đặt hàng
            model.Quantity = $("#ipQuantity").val();
            debugger;
            $.ajax({
                type: "POST",
                url: '@Url.Action("AddToCart", "Cart")',
                data:  JSON.stringify(model) ,
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function () {
                    alert("Thêm vào giỏ hàng thành công!")
                    $('#CartCount').text(@Session["count"] + 1);
                },
                error: function () {
                    alert("Lỗi khi thêm vào giỏ hàng!");
                }
            });
            return false;
        });
    });
</script>

<section class="py-3 bg-light">
    <div class="container">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="~/Home/Index">Trang chủ</a></li>
            <li class="breadcrumb-item active" aria-current="page">Chi tiết sản phẩm</li>
        </ol>
    </div>
</section>

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content bg-white padding-y">
    <div class="container">

        <!-- ============================ ITEM DETAIL ======================== -->
        <div class="row">
            <aside class="col-md-6">
                <div class="card">
                    <article class="gallery-wrap">
                        <div class="img-big-wrap">
                            <div> <a href="#"><img src="~/Content/images/items/@Model.Image"></a></div>
                        </div>
                    </article>
                </div>
            </aside>
            <main class="col-md-6">
                <article class="product-info-aside">

                    <h2 class="title mt-3">@Model.Name </h2>

                    <div class="rating-wrap my-3">
                        <ul class="rating-stars">
                            <li style="width:80%" class="stars-active">
                                <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                            </li>
                            <li>
                                <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i> <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                            </li>
                        </ul>
                        <small class="label-rating text-muted">132 đánh giá</small>
                        <small class="label-rating text-success"> <i class="fa fa-clipboard-check"></i> 154 đơn hàng </small>
                    </div>

                    <div class="mb-3">
                        <var class="price h4"></var>
                        <span class="text-muted">@Model.Price đã bao gồm thuế</span>
                    </div>
                    <dl class="row">
                        <dt class="col-sm-3">Nhà sản xuất</dt>
                        <dd class="col-sm-9"><a href="#">Great textile Ltd.</a></dd>

                        <dt class="col-sm-3">Số hiệu sản phẩm</dt>
                        <dd class="col-sm-9">596 065</dd>

                        <dt class="col-sm-3">Bảo hành</dt>
                        <dd class="col-sm-9">2 năm</dd>

                        <dt class="col-sm-3">Thời gian giao hàng</dt>
                        <dd class="col-sm-9">3-4 ngày</dd>

                        <dt class="col-sm-3">Tình trạng</dt>
                        <dd class="col-sm-9">Còn hàng</dd>
                    </dl>

                    <div class="form-row  mt-4">
                        <div class="form-group col-md flex-grow-0">
                            <div class="input-group mb-3 input-spinner">
                                <div class="input-group-prepend">
                                    <button class="btn btn-light" type="button" id="button-plus"> + </button>
                                </div>
                                <input type="text" id="ipQuantity" class="form-control" value="1">
                                <div class="input-group-append">
                                    <button class="btn btn-light" type="button" id="button-minus"> &minus; </button>
                                </div>
                            </div>
                        </div>
                        <div class="form-row  mt-4">
                            <div class="form-group col-md">
                                <a href="#" id="addtocart" class="btn  btn-primary">
                                    <i class="fas fa-shopping-cart"></i>
                                    <span class="text">Thêm vào giỏ hàng</span>
                                </a>
                            </div>
                        </div>
                    </div>

                </article>
            </main>
        </div>
    </div>
</section>

<!-- ========================= SECTION CONTENT END// ========================= -->
<section class="section-name padding-y bg">
    <div class="container">

        <div class="row">
            <div class="col-md-8">
                <h5 class="title-description">Mô tả</h5>
                <p>
                    @Model.FullDescription
                </p>
                @*<ul class="list-check">
                        <li>Chất liệu: Thép không gỉ</li>
                        <li>Cân nặng: 82kg</li>
                        <li>Được trang bị khay chứa nước</li>
                        <li>Có đáy mở cho nồi chảo</li>
                        <li>Có sẵn với phiên bản khí propan khi yêu cầu</li>
                    </ul>

                    <h5 class="title-description">Thông số kỹ thuật</h5>
                    <table class="table table-bordered">
                        <tr> <th colspan="2">Thông số cơ bản</th> </tr>
                        <tr> <td>Loại năng lượng</td><td>Đá núi lửa</td> </tr>
                        <tr> <td>Số lượng vùng</td><td>2</td> </tr>
                        <tr> <td>Kết nối tự động</td> <td> <i class="fa fa-check text-success"></i> Có </td></tr>

                        <tr> <th colspan="2">Kích thước</th> </tr>
                        <tr> <td>Chiều rộng</td><td>500mm</td> </tr>
                        <tr> <td>Chiều sâu</td><td>400mm</td> </tr>
                        <tr> <td>Chiều cao</td><td>700mm</td> </tr>

                        <tr> <th colspan="2">Vật liệu</th> </tr>
                        <tr> <td>Bề mặt ngoài</td><td>Thép không gỉ</td> </tr>
                        <tr> <td>Bên trong</td><td>Sắt</td> </tr>

                        <tr> <th colspan="2">Kết nối</th> </tr>
                        <tr> <td>Loại nhiệt</td><td>Khí</td> </tr>
                        <tr> <td>Công suất kết nối khí</td><td>15 Kw</td> </tr>

                    </table>*@
            </div>

            @*<aside class="col-md-4">

                        <div class="box">

                            <h5 class="title-description">Tài liệu</h5>
                            <p>
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                                tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                                quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                                consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                                cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                                proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                            </p>

                            <h5 class="title-description">Video</h5>

                            <article class="media mb-3">
                                <a href="#"><img class="img-sm mr-3" src="~/Content/images/posts/3.jpg"></a>
                                <div class="media-body">
                                    <h6 class="mt-0"><a href="#">Cách sử dụng sản phẩm này</a></h6>
                                    <p class="mb-2"> Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin </p>
                                </div>
                            </article>

                            <article class="media mb-3">
                                <a href="#"><img class="img-sm mr-3" src="~/Content/images/posts/2.jpg"></a>
                                <div class="media-body">
                                    <h6 class="mt-0"><a href="#">Mẹo và thủ thuật mới</a></h6>
                                    <p class="mb-2"> Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin </p>
                                </div>
                            </article>

                            <article class="media mb-3">
                                <a href="#"><img class="img-sm mr-3" src="~/Content/images/posts/1.jpg"></a>
                                <div class="media-body">
                                    <h6 class="mt-0"><a href="#">Mẹo và thủ thuật mới</a></h6>
                                    <p class="mb-2"> Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin </p>
                                </div>
                            </article>
                        </div>
                    </aside>
                </div>*@
        </div>
</section>

<section class="padding-y-lg bg-light border-top">
    <div class="container">

        <p class="pb-2 text-center">Cập nhật những xu hướng sản phẩm mới nhất và tin tức ngành nghề trực tiếp vào hộp thư của bạn</p>

        <div class="row justify-content-md-center">
            <div class="col-lg-4 col-sm-6">
                <form class="form-row">
                    <div class="col-8">
                        <input class="form-control" placeholder="Email của bạn" type="email">
                    </div>
                    <div class="col-4">
                        <button type="submit" class="btn btn-block btn-warning"> <i class="fa fa-envelope"></i> Đăng ký </button>
                    </div>
                </form>
                <small class="form-text">Chúng tôi sẽ không bao giờ chia sẻ email của bạn với bên thứ ba. </small>
            </div>
        </div>

    </div>
</section>