LeHungCuong_2122110266/Areas/Admin/Controllers/ProductController.cs
using LeHungCuong_2122110266.Context;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList.Mvc;
namespace LeHungCuong_2122110266.Areas.Admin.Controllers
{
    public class ProductController : Controller
    {

        WebAspDbEntities db = new WebAspDbEntities();

        // GET: Admin/Product
        public ActionResult Index(string Search, string currentFilter, int? page)
        {
            var listProduct = new List<Product>();
            if (Search != null)
            {
                page = 1;
            }
            else
            {
                Search = currentFilter;
            }
            if (!string.IsNullOrEmpty(Search))
            {
                listProduct = db.Product.Where(n => n.Name.Contains(Search)).ToList();
            }
            else
            {
                listProduct = db.Product.ToList();
            }
            ViewBag.CurrentFilter = Search;
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            listProduct = listProduct.OrderByDescending(n => n.Id).ToList();

            if (Request.IsAjaxRequest())
            {
                return PartialView("_ProductList", listProduct.ToPagedList(pageNumber, pageSize));
            }

            return View(listProduct.ToPagedList(pageNumber, pageSize));
        }
        [HttpGet]
        public ActionResult Create()
        {

            this.LoadData();

            return View();
        }
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult Create(Product product)
        {
            this.LoadData();
            if (ModelState.IsValid)
            {
                try
                {
                    if (product.ImageUpLoad != null && product.ImageUpLoad.ContentLength > 0)
                    {
                        string fileName = Path.GetFileNameWithoutExtension(product.ImageUpLoad.FileName);
                        string extension = Path.GetExtension(product.ImageUpLoad.FileName);
                        fileName = fileName + "_" + long.Parse(DateTime.Now.ToString("yyyyMMddhhmmss")) + extension;
                        product.Image = fileName;
                        product.ImageUpLoad.SaveAs(Path.Combine(Server.MapPath("~/Content/images/items/"), fileName));
                    }
                    product.CreatedAt = DateTime.Now;
                    db.Product.Add(product);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    return RedirectToAction("Index");
                }
            }
            return View(product);
        }


        [HttpGet]
        public ActionResult Details(int id)
        {
            var Product = db.Product.Where(n => n.Id == id).FirstOrDefault();
            return View(Product);
        }


        [HttpGet]
        public ActionResult Delete(int id)
        {
            var Product = db.Product.Where(n => n.Id == id).FirstOrDefault();
            return View(Product);
        }
        [HttpPost]
        public ActionResult Delete(Product product)
        {
            var Product = db.Product.Where(n => n.Id == product.Id).FirstOrDefault();
            db.Product.Remove(Product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var Product = db.Product.Where(n => n.Id == id).FirstOrDefault();
            return View(Product);
        }
        [HttpPost]
        public ActionResult Edit(Product product, int id)
        {
            var existingProduct = db.Product.Where(n => n.Id == id).FirstOrDefault();
            if (existingProduct == null)
            {
                return HttpNotFound();
            }


            if (product.ImageUpLoad != null && product.ImageUpLoad.ContentLength > 0)
            {
                // Nếu có hình mới, thực hiện lưu hình mới
                string fileName = Path.GetFileNameWithoutExtension(product.ImageUpLoad.FileName);
                string extension = Path.GetExtension(product.ImageUpLoad.FileName);
                fileName = fileName + "_" + long.Parse(DateTime.Now.ToString("yyyyMMddhhmmss")) + extension;
                product.Image = fileName;

                // Lưu hình vào thư mục
                product.ImageUpLoad.SaveAs(Path.Combine(Server.MapPath("~/Content/images/items/"), fileName));
            }
            else
            {
                // Nếu không có hình mới, giữ lại hình cũ
                product.Image = existingProduct.Image;
            }

            // Cập nhật các thông tin khác
            existingProduct.Name = product.Name;
            existingProduct.CategoryId = product.CategoryId;
            existingProduct.BrandId = product.BrandId;
            existingProduct.ShortDes = product.ShortDes;
            existingProduct.FullDescription = product.FullDescription;
            existingProduct.Price = product.Price;
            existingProduct.PriceDiscount = product.PriceDiscount;
            existingProduct.Deleted = product.Deleted;
            existingProduct.ShowOnHomePage = product.ShowOnHomePage;
            existingProduct.Image = product.Image; // Giữ hình cũ hoặc cập nhật hình mới
            existingProduct.UpdatedAt = DateTime.Now;



            db.Entry(existingProduct).State = EntityState.Modified;
            db.SaveChanges();

            return RedirectToAction("Index");
        }
        void LoadData()
        {
            Common objCommon = new Common();
            ListtoDataTableConverter converter = new ListtoDataTableConverter();

            var listCategory = db.Category.ToList();
            DataTable dtCategory = converter.ToDataTable(listCategory);
            ViewBag.ListCategory = objCommon.ToSelectList(dtCategory, "Id", "Name");

            var listBrands = db.Brand.ToList();
            DataTable dtBrands = converter.ToDataTable(listBrands);
            ViewBag.ListBrands = objCommon.ToSelectList(dtBrands, "Id", "Name");

            List<ProductType> listProductType = new List<ProductType>();
            ProductType productType = new ProductType();
            productType.Id = 1;
            productType.Name = "Giảm giá sốc";
            listProductType.Add(productType);

            productType = new ProductType();
            productType.Id = 2;
            productType.Name = "Đề xuất";
            listProductType.Add(productType);

            DataTable dtProductType = converter.ToDataTable(listProductType);
            ViewBag.ProductType = objCommon.ToSelectList(dtProductType, "Id", "Name");
        }
    }
}

LeHungCuong_2122110266/Controllers/ProductController.cs
using LeHungCuong_2122110266.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LeHungCuong_2122110266.Controllers
{
    public class ProductController : Controller
    {
        WebAspDbEntities db = new WebAspDbEntities();
        // GET: Product
        public ActionResult Detail(int Id)
        {
            var objProduct = db.Product.Where(n => n.Id == Id).FirstOrDefault();
            return View(objProduct);
        }
        public ActionResult ListingGrid()
        {
            return View();
        }
        public ActionResult ListingList(int Id, int page = 1, int pageSize = 1)
        {
            List<Product> listProduct;

            if (Id == 0) // Nếu ID là 0, lấy tất cả sản phẩm
            {
                listProduct = db.Product.ToList();
            }
            else
            {
                listProduct = db.Product.Where(n => n.CategoryId == Id).ToList();
            }

            // Tính tổng số sản phẩm
            int totalProducts = listProduct.Count;

            // Phân trang
            var paginatedProducts = listProduct.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            // Truyền dữ liệu cần thiết sang ViewBag
            ViewBag.CurrentCategoryId = Id;
            ViewBag.CurrentPage = page;
            ViewBag.TotalPages = (int)Math.Ceiling((double)totalProducts / pageSize);
            ViewBag.PageSize = pageSize;

            return View(paginatedProducts);
        }
    }
}

LeHungCuong_2122110266/Areas/Admin/Views/Product/Create.cshtml
@model LeHungCuong_2122110266.Context.Product

@{
    ViewBag.Title = "Create";
}
<script src="https://cdn.ckeditor.com/4.21.0/standard/ckeditor.js"></script>
<h2>Create</h2>

@using (Html.BeginForm("Create", "Product", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ImageUpLoad" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CategoryId, ViewBag.ListCategory as SelectList, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShortDes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShortDes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShortDes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FullDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.FullDescription, new { @class = "form-control", @id = "FullDecription" })
                @Html.ValidationMessageFor(model => model.FullDescription, "", new { @class = "text-danger" })
            </div>
            @*<script>
                // Đảm bảo CKEditor được khởi tạo sau khi trang được tải đầy đủ
                $(document).ready(function () {
                    CKEDITOR.replace('FullDecription');

                    // Đảm bảo CKEditor có thể gửi dữ liệu vào form khi submit
                    $('form').submit(function () {
                        // Cập nhật giá trị của CKEditor vào textarea khi form được submit
                        for (instance in CKEDITOR.instances) {
                            CKEDITOR.instances[instance].updateElement();
                        }
                    });
                });
            </script>*@

        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PriceDiscount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PriceDiscount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PriceDiscount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TypeId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.TypeId, ViewBag.ProductType as SelectList, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TypeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Slug, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Slug, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Slug, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BrandId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.BrandId, ViewBag.ListBrands as SelectList, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BrandId, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay về", "Index")
</div>

LeHungCuong_2122110266/Areas/Admin/Views/Product/Delete.cshtml
@model LeHungCuong_2122110266.Context.Product

@{
    ViewBag.Title = "Delete";
}

<h2 class="text-danger">Xóa sản phẩm</h2>

<div class="alert alert-warning">
    <h4><i class="fas fa-exclamation-triangle"></i> bạn có chắc muốn xóa sản phẩm này?</h4>
    <p>This action cannot be undone.</p>
</div>

<div class="card">
    <div class="card-header bg-danger text-white">
        <h5>Product Details</h5>
    </div>
    <div class="card-body">
        <dl class="row">
            <dt class="col-sm-3 font-weight-bold">
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt class="col-sm-3 font-weight-bold">
                @Html.DisplayNameFor(model => model.Image)
            </dt>
            <dd class="col-sm-9">
                <img src="@Url.Content("~/Content/images/items/" + Model.Image)" alt="Product Image" class="img-thumbnail" style="max-width: 150px;" />
            </dd>

            <dt class="col-sm-3 font-weight-bold">
                @Html.DisplayNameFor(model => model.CategoryId)
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.CategoryId)
            </dd>

            <dt class="col-sm-3 font-weight-bold">
                @Html.DisplayNameFor(model => model.ShortDes)
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.ShortDes)
            </dd>

            <dt class="col-sm-3 font-weight-bold">
                @Html.DisplayNameFor(model => model.Price)
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.Price) $
            </dd>

            <dt class="col-sm-3 font-weight-bold">
                @Html.DisplayNameFor(model => model.CreatedAt)
            </dt>
            <dd class="col-sm-9">
                @Html.DisplayFor(model => model.CreatedAt)
            </dd>
        </dl>
    </div>
</div>

<div class="mt-4">
    @using (Html.BeginForm("Delete", "Product", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <input type="hidden" name="id" value="@Model.Id" />

        <div class="text-center">
            <button type="submit" class="btn btn-danger">
                <i class="fas fa-trash-alt"></i> xóa
            </button>
            <a href="@Url.Action("Index", "Product")" class="btn btn-secondary">
                <i class="fas fa-arrow-left"></i> Quay về
            </a>
        </div>
    }
</div>

LeHungCuong_2122110266/Areas/Admin/Views/Product/Details.cshtml
@model LeHungCuong_2122110266.Context.Product

@{
    ViewBag.Title = "Details";
}

<div class="container mt-4">
    <div class="card shadow-sm">
        <div class="card-header bg-primary text-white">
            <h3 class="mb-0">Chi tiết</h3>
        </div>
        <div class="card-body">
            <h4 class="text-muted">Chi tiết sản phẩm</h4>
            <hr />
            <div class="row">
                <div class="col-md-6">
                    <dl class="row">
                        <dt class="col-sm-4">tên</dt>
                        <dd class="col-sm-8">@Html.DisplayFor(model => model.Name)</dd>

                        <dt class="col-sm-4">ảnh</dt>
                        <dd class="col-sm-8">
                            <img src="@Url.Content("~/Content/images/items/" + Model.Image)" alt="Product Avatar" class="img-fluid rounded" />
                        </dd>

                        <dt class="col-sm-4">danh mục</dt>
                        <dd class="col-sm-8">@Html.DisplayFor(model => model.CategoryId)</dd>

                        <dt class="col-sm-4">mô tả ngắn</dt>
                        <dd class="col-sm-8">@Html.DisplayFor(model => model.ShortDes)</dd>

                        <dt class="col-sm-4">mô tả đủ</dt>
                        <dd class="col-sm-8">@Html.DisplayFor(model => model.FullDescription)</dd>
                    </dl>
                </div>

                <div class="col-md-6">
                    <dl class="row">
                        <dt class="col-sm-4">giá</dt>
                        <dd class="col-sm-8">@Html.DisplayFor(model => model.Price)</dd>

                        <dt class="col-sm-4">Giá giảm</dt>
                        <dd class="col-sm-8">@Html.DisplayFor(model => model.PriceDiscount)</dd>

                        <dt class="col-sm-4">loại</dt>
                        <dd class="col-sm-8">@Html.DisplayFor(model => model.TypeId)</dd>

                        <dt class="col-sm-4">Slug</dt>
                        <dd class="col-sm-8">@Html.DisplayFor(model => model.Slug)</dd>

                        <dt class="col-sm-4">thương hiệu</dt>
                        <dd class="col-sm-8">@Html.DisplayFor(model => model.BrandId)</dd>
                    </dl>
                </div>
            </div>

            <h4 class="text-muted mt-4">thông tin thêm</h4>
            <hr />
            <dl class="row">
                <dt class="col-sm-3">xóa</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.Deleted)</dd>

                <dt class="col-sm-3">hiển thị</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.ShowOnHomePage)</dd>


                <dt class="col-sm-3">Ngày tạo</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.CreatedAt)</dd>

                <dt class="col-sm-3">Ngày cập nhật</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.UpdatedAt)</dd>
            </dl>
        </div>
        <div class="card-footer text-end">
            @Html.ActionLink("Chỉnh sữa", "Edit", new { id = Model.Id }, new { @class = "btn btn-primary me-2" })
            @Html.ActionLink("Quay về", "Index", null, new { @class = "btn btn-secondary" })
        </div>
    </div>
</div>

LeHungCuong_2122110266/Areas/Admin/Views/Product/Edit.cshtml
@model LeHungCuong_2122110266.Context.Product

@{
    ViewBag.Title = "Edit";
}

<h2 class="text-center mb-4">Chỉnh sữa sản phẩm</h2>

@using (Html.BeginForm("Edit", "Product", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="container">
        <div class="card shadow-sm">
            <div class="card-body">
                <h4 class="card-title">Chỉnh sữa</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "alert alert-danger" })
                @Html.HiddenFor(model => model.Id)
                @Html.HiddenFor(model => model.CreatedAt)
                <div class="row mb-3">
                    <label class="col-md-3 col-form-label">@Html.LabelFor(model => model.Name)</label>
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row mb-3">
                    <label class="col-md-3 col-form-label">@Html.LabelFor(model => model.Image)</label>
                    <div class="col-md-9">
                        <!-- Hiển thị hình ảnh hiện tại -->
                        @if (!string.IsNullOrEmpty(Model.Image))
                        {
                            <img src="~/Content/images/items/@Model.Image" alt="Current Image" class="img-thumbnail" style="max-width: 200px;" />
                        }
                        <input type="file" name="ImageUpLoad" class="form-control mt-2" />
                    </div>
                </div>


                <div class="row mb-3">
                    <label class="col-md-3 col-form-label">@Html.LabelFor(model => model.CategoryId)</label>
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.CategoryId, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row mb-3">
                    <label class="col-md-3 col-form-label">@Html.LabelFor(model => model.BrandId)</label>
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.BrandId, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.BrandId, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row mb-3">
                    <label class="col-md-3 col-form-label">@Html.LabelFor(model => model.ShortDes)</label>
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.ShortDes, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ShortDes, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row mb-3">
                    <label class="col-md-3 col-form-label">@Html.LabelFor(model => model.FullDescription)</label>
                    <div class="col-md-9">
                        @Html.TextAreaFor(model => model.FullDescription, new { @class = "form-control", rows = 4 })
                        @Html.ValidationMessageFor(model => model.FullDescription, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row mb-3">
                    <label class="col-md-3 col-form-label">@Html.LabelFor(model => model.Price)</label>
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row mb-3">
                    <label class="col-md-3 col-form-label">@Html.LabelFor(model => model.PriceDiscount)</label>
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.PriceDiscount, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PriceDiscount, "", new { @class = "text-danger" })
                    </div>
                </div>

                <!-- Checkbox Inputs -->
                <div class="row mb-3">
                    <label class="col-md-3 col-form-label">@Html.LabelFor(model => model.Deleted)</label>
                    <div class="col-md-9">
                        <div class="form-check">
                            @Html.EditorFor(model => model.Deleted)
                            @Html.ValidationMessageFor(model => model.Deleted, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="row mb-3">
                    <label class="col-md-3 col-form-label">@Html.LabelFor(model => model.ShowOnHomePage)</label>
                    <div class="col-md-9">
                        <div class="form-check">
                            @Html.EditorFor(model => model.ShowOnHomePage)
                            @Html.ValidationMessageFor(model => model.ShowOnHomePage, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>


                <!-- Submit Button -->
                <div class="row">
                    <div class="col-md-9 offset-md-3">
                        <button type="submit" class="btn btn-primary">Lưu</button>
                        @Html.ActionLink("Quay về", "Index", null, new { @class = "btn btn-secondary ms-2" })
                    </div>
                </div>
            </div>
        </div>
    </div>
}

LeHungCuong_2122110266/Areas/Admin/Views/Product/Index.cshtml
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<LeHungCuong_2122110266.Context.Product>

<h2>Quản lý sản phẩm</h2>

<p>
    @Html.ActionLink("Thêm sản phẩm", "Create", null, new { @class = "btn btn-primary" })
</p>
@using (Html.BeginForm("Index", "Product", FormMethod.Get, new { id = "searchForm" }))
{
    <p>
        Tìm tên sản phẩm: @Html.TextBox("Search", ViewBag.CurrentFilter as string, new { id = "searchBox" })
        <input type="submit" value="Tìm kiếm" />
    </p>
}

<div id="productList">
    @Html.Partial("_ProductList", Model)
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    // Xử lý tìm kiếm bằng AJAX
    $("#searchForm").on("submit", function (e) {
        e.preventDefault();
        var url = $(this).attr("action");
        var query = $("#searchBox").val();

        $.get(url, { Search: query }, function (data) {
            $("#productList").html(data);
        });
    });

    // Xử lý phân trang bằng AJAX
    $(document).on("click", ".pagination a", function (e) {
        e.preventDefault();
        var url = $(this).attr("href");

        $.get(url, function (data) {
            $("#productList").html(data);
        });
    });
</script>

LeHungCuong_2122110266/Areas/Admin/Views/Product/Product.cshtml
@model IEnumerable<LeHungCuong_2122110266.Context.Product>

@{
    ViewBag.Title = "Product";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CategoryId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BrandId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ShortDes)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ShowOnHomePage)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FullDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PriceDiscount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TypeId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Slug)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedAt)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UpdatedAt)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Deleted)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Image)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CategoryId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BrandId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ShortDes)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ShowOnHomePage)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FullDescription)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PriceDiscount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TypeId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Slug)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedAt)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UpdatedAt)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Deleted)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>